import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mac(props) {
  const { nodes, materials } = useGLTF('/mac.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.yIwQWXMhgFCUjXk.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BcjQsesUEBYnKoM.geometry}
          material={materials.AibnXCKcAbewWhH}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BMRxbFrXdGVXapn.geometry}
          material={materials.WeLyzRwUVIhQGgM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.bULwzZWcFpZxJkG.geometry}
          material={materials.UhoCLqHkvkDmxOA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CJAQSkFmaCOLnah.geometry}
          material={materials.zhGRTuGrQoJflBD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.dcJxdlEFKMVLbfj.geometry}
          material={materials.zCLdUynNQOzVMqx}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DXClxamwHRBRJcJ.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.eEDJDQDQQpAlFLR.geometry}
          material={materials.lmWQsEjxpsebDlK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EkEhIUqwYBQVZUT.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EkfKXxkPaSHjDtP.geometry}
          material={materials.MycfwscjQZRVSoj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FoxumPUtvMVSIQz.geometry}
          material={materials.bsmYIMHYRqMuLqz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FYHusgfNSPjDjSu.geometry}
          material={materials.LtEafgAVRolQqRw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.gBoAkeTtukenhWq.geometry}
          material={materials.iyDJFXmHelnMTbD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HgNMqanjwlZZAOv.geometry}
          material={materials.eJObPwhgFzvfaoZ}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HKglYOjqEuUiDcK.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hspaCPnSDNUJHAG.geometry}
          material={materials.nDsMUuDKliqGFdU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HZDoNBZMZsNTsVe.geometry}
          material={materials.LtEafgAVRolQqRw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.iikabETxQFfJEem.geometry}
          material={materials.CRQixVLpahJzhJc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.jcWJTOAOShYbccw.geometry}
          material={materials.IcpudUyxprDYhfw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.JexNBRezsJZplFU.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.khECtsAtHglteMB.geometry}
          material={materials.YYwBgwvcyZVOOAA}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LttXdHRCykGpOyb.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MLLCVeaLPFKfpMI.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.MSvtIRGpODFmbIn.geometry}
          material={materials.SLGkCohDDelqXBu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mYemcOocmDhPlUX.geometry}
          material={materials.WDumMKBWVQxmraD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.OXjUsVQnIlkDrZa.geometry}
          material={materials.WnHKXHhScfUbJQi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pVvVRTSPvpyfGNE.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QgXnkTZyDqCQpCk.geometry}
          material={materials.ZNhRrZtaKWQYAab}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rMhEQHgWLZWXzLG.geometry}
          material={materials.IcpudUyxprDYhfw}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RyWgIoOOwmdKlnQ.geometry}
          material={materials.fNHiBfcxHUJCahl}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SDuwtEsnNduSSwf.geometry}
          material={materials.bsEIHfblEXNcUMs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sQoYyGpBtOFkxlB.geometry}
          material={materials.CRQixVLpahJzhJc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TLIJmrBJnDhoxJE.geometry}
          material={materials.SABLxXNNESCdgUy}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TqfPCmGXMEJttDv.geometry}
          material={materials.LpqXZqhaGCeSzdu}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.UJKMWhpvMdqjnoM.geometry}
          material={materials.sIfSZcqgDlKMJPf}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vAuyxjZlaAwXIiI.geometry}
          material={materials.bsmYIMHYRqMuLqz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wAdQYvpjiXvjpyn.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XFrrJGMTkvjIPfX.geometry}
          material={materials.gMtYExgrEUqPfln}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XmEJWcRmlkotJdx.geometry}
          material={materials.WnHKXHhScfUbJQi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.yEmivVbIjwnyaON.geometry}
          material={materials.nDsMUuDKliqGFdU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.YVNCsLxwBXwECqt.geometry}
          material={materials.bsEIHfblEXNcUMs}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZABjfAfCTFAnCJS.geometry}
          material={materials.uInNDOueKeBTGQB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.zGmuvzWlQjLoXZb.geometry}
          material={materials.hmEmmncwVomyUTC}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZUCWPMnPNxOkCew.geometry}
          material={materials.WeLyzRwUVIhQGgM}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZWfiEHODMuFnYim.geometry}
          material={materials.KclpPzxoRwZAoer}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.aXVtPPoMqmRgmzr.geometry}
          material={materials.wjAYtisbflXilXi}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AYYuaeHOoOzRBFD.geometry}
          material={materials.zobIbiekuagXEVU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.EsQRFXIuhhkXDHc.geometry}
          material={materials.RyKTMHTpkkwQkvB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fPdibardHSJwjJd.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hfzIrgDnZGUCeIf.geometry}
          material={materials.JvMFZolVCdpPqjj}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hHhPbaoMyEYnAtT.geometry}
          material={materials.UBYmHfGRfHbOXyc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.JmtTIxqGsWGahBm.geometry}
          material={materials.uInNDOueKeBTGQB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pcXqdAGEOhKeaFf.geometry}
          material={materials.gOXiFODBFKnUyyU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rkvrbfDCpwDXEyy.geometry}
          material={materials.eBwkWuOBScacrgP}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.terweEiSWGhyRJE.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.USdQzuJXNMiomIw.geometry}
          material={materials.jwuTsnFxKtBUxpK}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.VDAbKiEOmWyaWvX.geometry}
          material={materials.nDsMUuDKliqGFdU}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vttfLwUKvlhvIxZ.geometry}
          material={materials.CdgEAaPUlrQWQuD}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wAiStilElLYteOj.geometry}
          material={materials.ZCDwChwkbBfITSW}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XlcvJOqSiZcqDDS.geometry}
          material={materials.XCYkeTCxqFmKTKe}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ZtDnMGoWGySWyjB.geometry}
          material={materials.MycfwscjQZRVSoj}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vttfLwUKvlhvIxZ001.geometry}
          material={materials['CdgEAaPUlrQWQuD.001']}
          position={[-0.186, -0.109, -0.334]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hello.geometry}
        material={nodes.hello.material}
        position={[-12.442, 17.343, -12.121]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[21.461, 25, 22.667]}
      />
    </group>
  )
}

useGLTF.preload('/mac.glb')
